-- ============================================================
-- PROJET FINAL ORACLE - GESTION E-COMMERCE
-- Script 02 : Séquences pour l'auto-incrémentation des IDs
-- ============================================================

BEGIN
    FOR s IN (SELECT sequence_name FROM user_sequences
              WHERE sequence_name IN ('SEQ_CATEGORIES','SEQ_FOURNISSEURS','SEQ_PRODUITS',
                                      'SEQ_CLIENTS','SEQ_COMMANDES','SEQ_LIGNES_COMMANDE',
                                      'SEQ_PAIEMENTS','SEQ_LIVRAISONS')) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
END;
/

CREATE SEQUENCE SEQ_CATEGORIES    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FOURNISSEURS  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUITS      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CLIENTS       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COMMANDES     START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LIGNES_COMMANDE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PAIEMENTS     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LIVRAISONS    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMIT;