PROMPT Rafraîchissement de MV_CA_PAR_MOIS...
EXEC DBMS_MVIEW.REFRESH('MV_CA_PAR_MOIS', 'C');
PROMPT Rafraîchissement de MV_TOP_PRODUITS...
EXEC DBMS_MVIEW.REFRESH('MV_TOP_PRODUITS', 'C');
PROMPT Rafraîchissement de MV_STATS_CLIENTS...
EXEC DBMS_MVIEW.REFRESH('MV_STATS_CLIENTS', 'C');
PROMPT Toutes les vues matérialisées ont été rafraîchies.
EXIT;