SET PAGESIZE 50 LINESIZE 100
PROMPT ============================================================
PROMPT  VERIFICATION DES DONNEES
PROMPT ============================================================
SELECT 'CATEGORIES' AS table_nom, COUNT(*) AS nb_lignes FROM CATEGORIES UNION ALL
SELECT 'FOURNISSEURS', COUNT(*) FROM FOURNISSEURS UNION ALL
SELECT 'PRODUITS', COUNT(*) FROM PRODUITS UNION ALL
SELECT 'CLIENTS', COUNT(*) FROM CLIENTS UNION ALL
SELECT 'COMMANDES', COUNT(*) FROM COMMANDES UNION ALL
SELECT 'LIGNES_COMMANDE', COUNT(*) FROM LIGNES_COMMANDE UNION ALL
SELECT 'PAIEMENTS', COUNT(*) FROM PAIEMENTS UNION ALL
SELECT 'LIVRAISONS', COUNT(*) FROM LIVRAISONS;
PROMPT ============================================================
PROMPT  VERIFICATION DES VUES MATERIALISEES
PROMPT ============================================================
SELECT COUNT(*) AS nb_lignes_MV_CA_PAR_MOIS FROM MV_CA_PAR_MOIS;
SELECT COUNT(*) AS nb_lignes_MV_TOP_PRODUITS FROM MV_TOP_PRODUITS;
SELECT COUNT(*) AS nb_lignes_MV_STATS_CLIENTS FROM MV_STATS_CLIENTS;
EXIT;